# Configuration file for DeathFeathers
# https://www.spigotmc.org/resources/deathfeathers.30530/
# Created by KevinNovak

# ============================================
# Item
# ============================================
# The item which can be used to find your last death location
# must be an item name, by default a feather
# A list of item names can be found here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# default: item: FEATHER
item: FEATHER

# Should the item that is given upon death be named?
# default: itemNameEnabled: true
itemNameEnabled: true

# Should the named version of the item be required,
# in order to show the death location distance?
# default: itemNameRequired: true
itemNameRequired: true

# What should the item be named?
# Color codes are supported here
# default: itemName: '&6Death Feather'
itemName: '&6Death Feather'

# Should the item that is given upon death have lore?
# default: itemLoreEnabled: true
itemLoreEnabled: true

# What should the items lore be?
# Color codes are supported here
# default: itemLore:
#- '&3Left click to show distance'
#- '&3Right click to show path'
itemLore:
  - '&3Left click to show distance'
  - '&3Right click to show path'

# Should players be given the item when they respawn?
# default: itemOnRespawn: true
itemOnRespawn: true

# Should compasses point to players last death locations?
# If you would also like players to click with a compass for distance,
# then change the "item" above to be a compass, item ID 345
# default: compassDirection: false
compassDirection: false

# Should distances be calculated in 3 dimensions instead of 2?
# in other words, should height count towards distance?
# default: distance3D: false
distance3D: false

# ============================================
# Controls
# ============================================
# Which mouse button should the above item use for finding distance?
# it is possible to use both or neither here, if desired
# default: leftClick: true
# default: rightClick: false
leftClick: true
rightClick: false

# Which mouse button should the above item use for showing particles paths?
# it is possible to use both or neither here, if desired
# default: leftClickParticles: false
# default: rightClickParticles: true
leftClickParticles: false
rightClickParticles: true

# The distance away from the player to start and stop showing particles
# Distance is in number of blocks
# Stop distance must be larger than start distance
# default: particleStartDistance: 0
# default: particleStopDistance: 12
particleStartDistance: 0
particleStopDistance: 12

# ============================================
# Teleportation
# ============================================
# The time, in seconds, to wait before teleporting to a players death location
# can be bypassed with the permission deathfeathers.tp.bypass
# or set to 0 to disable completely
# default: delaySeconds: 5
delaySeconds: 5

# The time, in seconds, before a player can use /tpdeath or /tpdeath <player>
# can be bypassed with the permission deathfeathers.tp.bypass
# or set to 0 to disable completely
# default: cooldownSeconds: 3600
cooldownSeconds: 3600

# When players teleport to a death location,
# how many blocks above should they teleport?
# This is to prevent accidentally picking up a players items
# by default 0, meaning you will pick up any nearby items
# 1 works well to avoid picking up items
# default: numBlocksAbove: 0
numBlocksAbove: 0

# ============================================
# Logging
# ============================================
# Whether the console should log players death locations.
# default: consoleLog: true
consoleLog: true

# ============================================
# General Language
# ============================================
# for senddistance, place the variable "{DISTANCE}" where you would like the distance
# default: senddistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
sendDistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
# for teleporting, place the variable "{DELAY}" where you would like the delay time
# default: teleporting: '&7Teleporting in {DELAY} seconds...'
teleporting: '&7Teleporting in {DELAY} seconds...'
# for cooldown, place the variable "{COOLDOWN}" where you would like the cooldown time
# default: cooldown: '&7You must wait {COOLDOWN}.'
cooldown: '&7You must wait {COOLDOWN}.'
# for deathlog, place the variables "{PLAYER}", "{LOCATION}", and "{WORLD}" where you'd like
# default: deathlog: '{PLAYER} has died at {LOCATION} in {WORLD}.'
deathLog: '&7{PLAYER} has died at &6{LOCATION} &7in {WORLD}.'
notPermitted: '&cYou are not permitted to do this!'
notDied: '&cYou have not yet died!'
anotherWorld: '&cYour death location is in another world!'
tpWait: '&cYou are already teleporting!'
noConsole: '&cConsole cannot run DeathFeathers commands!'
noLocation: '&cPlayer death location not found!'

# ============================================
# Help Menu Language
# ============================================
helpHeader: ' &e------------- &6Death Feathers &e-------------'
helpFooter: ' &e----------------------------------------'
helpNoCommands: '&7 You are not allowed to use commands.'
# for helpPage, place the variable "{PAGE}" where you would like the next page number
# default: helpPage: '&7 Type &6/df {PAGE} &7for more info.'
helpPage: '&7 Type &6/df {PAGE} &7for more info.'
helpFindDeath: '&b/finddeath &7- Show distance to your death.'
helpTpDeath: '&b/tpdeath &7- Teleport to your death.'
helpTpDeathOther: '&b/tpdeath <player> &7- Teleport to a players death.'

# ============================================
# Variable Langauge
# ============================================
day: 'day'
days: 'days'
hour: 'hour'
hours: 'hours'
minute: 'minute'
minutes: 'minutes'
second: 'second'
seconds: 'seconds'
